linters:
  enable:
    - exportloopref
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  whitespace:
    multi-func: true